language: node_js
notifications:
  email: false
before_install: if npm --version | grep '^[34]' ; then npm install npm@latest -g ; fi
node_js:
  - "10"
  - "8"
  - "6"
script:
  - npm run report-coverage
  - npm run bench 0.25
